# Generated by Django 4.2.11 on 2024-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dag',
            name='schedule_interval_cron',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
