# Generated by Django 4.2.11 on 2024-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dags', '0003_alter_dag_contact_email_alter_dag_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='depends_on',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
